source 'https://rubygems.org'


gem 'rails', '4.2.4'

gem 'rails-api'

gem 'spring', :group => :development

gem 'rest-client'

gem 'pg'

gem 'rspec-rails'

# clear syntax for writing and deploying cron jobs
gem 'whenever', :require => false

gem 'pry'


# be able to render json using views
# gem 'rabl'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
