# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 558b3a025a1671e540c5ea6ba8c4e5b5bec535554e4f28c9b9f2276c24c4f708e04f0298e2071bb8cc0b25119341b18ecdf50d3eaa4ac47205a410fce80fe0c5

test:
  secret_key_base: be295e506cbccfa507661557b04a0319a368e7a57ed568576d3d06c582964fccc18b970c0138a8844f7dc2c6785e1043944ce511952812bba79894f786d1d387

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
