# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeca345e6c43a419c9b947cdc733708883cebb05c542e8443e7748d8af6ec8fc8324e74310e182edb91888ec810189051777f8add92b83ca079199945f16ac5a

test:
  secret_key_base: 4d04a0316e86409ed7788916dfd968817dcc2892722b75487b695c64e91b10dedde82bb1b9ac3998d294852c4f65b2bd095b72c4a2d196677e5162b03ea56570

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
