# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5429e6dac3084b567213f89ec629c476a87118e08f1af3fede93e3767e0c2efa40c6b835f6df615fe974508d9aa08964ca5da4a7628048e0288dd9e718cf464

test:
  secret_key_base: d0af5ac2115cf7e18fb0192d84c47ab4005280ed62fd0cb4de31b25245a35e360db5046ebaba555385ce7099f4115c9453773ccccd147e51b3fa874af84d1603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
